# Generated by Django 4.2.9 on 2024-01-31 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_driver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=20)),
                ('max_passengers', models.PositiveIntegerField()),
                ('additional_info', models.TextField(blank=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rides.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_location', models.TextField()),
                ('destination_address', models.TextField()),
                ('arrival_datetime', models.DateTimeField()),
                ('total_passengers', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(blank=True, max_length=255)),
                ('shared_ride', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('finished', 'Finished')], default='request', max_length=20)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driven_rides', to='rides.userprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rides', to='rides.userprofile')),
                ('sharers', models.ManyToManyField(blank=True, related_name='shared_rides', to='rides.userprofile')),
            ],
        ),
    ]
