# Generated by Django 4.2.9 on 2024-01-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('finished', 'Finished')], default='open', max_length=20),
        ),
    ]
