# Generated by Django 4.2.9 on 2024-02-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='driver_status',
            field=models.BooleanField(default=False),
        ),
    ]
